# Generated by Django 3.1.5 on 2021-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_auto_20210222_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notetext',
            field=models.CharField(default='', max_length=100),
        ),
    ]
