# Generated by Django 3.1.5 on 2021-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_note_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notetext',
            new_name='note_title',
        ),
        migrations.AddField(
            model_name='note',
            name='note_description',
            field=models.TextField(default=''),
        ),
    ]
